# Generated by Django 4.1.7 on 2023-04-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='convert_currency',
            new_name='converting_currency',
        ),
    ]
