# Generated by Django 4.1.7 on 2023-03-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='Currency_type',
            field=models.CharField(choices=[('UK Pounds', 'GBP'), ('US Dollars', 'USD'), ('EUro', 'EUR')], default='GBP', max_length=10),
        ),
    ]
