# Generated by Django 4.1.7 on 2023-03-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_user_profile_currency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
