# Generated by Django 4.1.7 on 2023-04-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_user_profile_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='Currency_type',
            field=models.CharField(choices=[('GBP', 'UK Pounds'), ('USD', 'US Dollars'), ('EUro', 'EUro')], default='GBP', max_length=10),
        ),
    ]
