# Generated by Django 4.1.7 on 2023-03-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_history_transaction_transcation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcation',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transcation',
            name='recipient',
            field=models.CharField(max_length=50),
        ),
    ]
