# Generated by Django 4.1.7 on 2023-03-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_alter_transcation_amount_alter_transcation_recipient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='history_transaction',
        ),
        migrations.AddField(
            model_name='transcation',
            name='transer_status',
            field=models.CharField(choices=[('w', 'Wait for approval'), ('s', 'successful'), ('d', 'declined')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='transcation',
            name='transfer_type',
            field=models.CharField(choices=[('send', 'Send'), ('request', 'Request')], default='', max_length=10),
        ),
    ]
