# Generated by Django 4.1.7 on 2023-03-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0005_alter_transcation_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcation',
            old_name='transer_status',
            new_name='transfer_status',
        ),
    ]
