# Generated by Django 4.1.7 on 2023-03-23 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payapp', '0006_rename_transer_status_transcation_transfer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcation',
            name='transfer_status',
            field=models.CharField(choices=[('successful', 'successful'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='s', max_length=10),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('declined', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(max_length=100)),
                ('transfer_status', models.CharField(choices=[('w', 'Wait for approval'), ('s', 'successful'), ('d', 'declined')], default='', max_length=10)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
