# Generated by Django 4.1.7 on 2023-04-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0010_transcation_reference_alter_request_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcation',
            name='transfer_status',
        ),
        migrations.AlterField(
            model_name='request',
            name='transfer_status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
